Repository FIAP-7/TECH-CHALLENGE, pull requests merged in 2025-08, with the labels that each got.

#58 #47 docs: atualizar endpoints e exemplos
  documentacao/TechChallenge_GestãoRestaurantes.pdf
Labels: Status: Em Revisão

#57 fix: #55 ajuste retorno registros inexistentes
  src/main/java/br/com/fiap/postech/gestao_restaurantes/core/controller/TipoUsuarioCoreController.java
  src/main/java/br/com/fiap/postech/gestao_restaurantes/core/controller/UsuarioCoreController.java
Labels: Erro: Git semântico inválido, Status: Em Revisão

#71 #69 feat: TU restaurante e item cardápio
  src/main/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/itemCardapio/AtualizarItemCardapioUseCase.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/itemCardapio/AtualizarItemCardapioUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/itemCardapio/ConsultarItemCardapioUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/itemCardapio/CriarItemCardapioUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/itemCardapio/DeletarItemCardapioUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/restaurante/AtualizarRestauranteUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/restaurante/ConsultarRestauranteUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/restaurante/CriarRestauranteUseCaseTest.java
  src/test/java/br/com/fiap/postech/gestao_restaurantes/core/usecase/restaurante/DeletarRestauranteUseCaseTest.java
Labels: Status: Em Revisão

#75 #72 style: Remoção de comentarios e codigos comentados.
  src/main/java/br/com/fiap/postech/gestao_restaurantes/core/entities/TipoUsuario.java
  src/main/java/br/com/fiap/postech/gestao_restaurantes/infra/controller/TipoUsuarioController.java
  src/main/java/br/com/fiap/postech/gestao_restaurantes/infra/controller/UsuarioController.java
Labels: Status: Finalizada, Ambiente: Produção
